blank_issues_enabled: true
contact_links:
  - name: Zoid Support
    url: https://t.me/Zoidsupport
    about: Please drop your doubts or queries there for an immediate response.
  - name: Documentation
    url: https://ZoidUbot.tech/
    about: Basic documentation for setting up.
